### ISSUE TITLE
Xcode 10 Swift 4.2 compiler error

### ISSUE THREAD

**Issue by mrhaxic** [MessageKit/MessageKit#871]
- What version of MessageKit are you using? master branch
- What version of iOS are you running on? iOS 12
- What version of Swift are you running on? 4.2
- What device(s) are you testing on? Are these simulators? Simulator
- Is the issue you're experiencing reproducable in the example app?

In some cases it can be really helpful to provide a short example of your code.
If so, please wrap these code blocks in backticks, like this:

```swift
Undefined symbols for architecture x86_64:
  "MessageKit.MessageLabel.defaultAttributes.unsafeMutableAddressor : Swift.Dictionary<__C.NSAttributedStringKey, Any>", referenced from:
      Movieiness.ConversationViewController.detectorAttributes(for: MessageKit.DetectorType, and: MessageKit.MessageType, at: Foundation.IndexPath) -> Swift.Dictionary<__C.NSAttributedStringKey, Any> in ConversationViewController.o
ld: symbol(s) not found for architecture x86_64
```

**Comment by mrhaxic** [comment]
I found the below solution, what do you think?

```swift
  func detectorAttributes(for detector: DetectorType, and message: MessageType, at indexPath: IndexPath) -> [NSAttributedStringKey: Any] {
        //return MessageLabel.defaultAttributes
        var attributes : [NSAttributedStringKey : Any] = [:]
        attributes[NSAttributedStringKey.foregroundColor] = UIColor.darkText
        attributes[NSAttributedStringKey.underlineStyle] = NSUnderlineStyle.styleSingle.rawValue
        attributes[NSAttributedStringKey.underlineColor] = UIColor.darkText
        return attributes
    }
```

**Comment by SD10** [comment]
We're working on Swift 4.2 support @mrhaxic 👍 Thanks for opening this

**Comment by gorbat-o** [comment]
Hey @SD10 
is there any branch for Swift 4.2 that we can use to anticipate the update ?

Thanks

EDIT: I found this haha
![image](https://user-images.githubusercontent.com/7542553/45927335-fb95c780-bf31-11e8-880a-cc63bc388ea2.png)
I will try the secret branch ;) 

EDIT2: MessageInputBar is not updated in any branch :/

**Comment by nathantannar4** [comment]
I can push some updates for MessageInputBar. One can be an update to 4.2

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gorbat-o** [comment]
Hey, I did a fork on my side, if needed I can create a PR for MessageInputBar

**Comment by nathantannar4** [comment]
@gorbat-o I have quite a few bugs and updates to merge first

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gorbat-o** [comment]
No problem :)

**Comment by SD10** [comment]
lol I'm using `sd10/MessageKit secret-branch` for work right now 😂 Very dangerous branch to use because it's whatever I need it to be

**Comment by nathantannar4** [comment]
My updates on MessageInputBar are on `port-updates`

**Comment by gorbat-o** [comment]
the day it will be released, it is going to be fun 😂

**Comment by nathantannar4** [comment]
@gorbat-o https://github.com/MessageKit/MessageInputBar/tree/swift4.2
Just specify the branch in your pod file

**Comment by Tak783** [comment]
What i've found (since the same issue appears when i update my pods) is to into the pod, open build settings and set the version of swift to 4.2, then it just works. So when i update cocoa pods message kit comes through in swift 4.0. My project is currently swift 4.2.

**Comment by nathantannar4** [comment]
@Guy783 Please do not ask duplicate questions in separate threads. You already asked this in #975

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
